=== Shraggen/XML/xml-content/database/database.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="energie-data">
        <xs:complexType>
            <xs:all>
                <xs:element ref="energie-plant"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="energie-plant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="plant" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="plant">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="status" type="xs:boolean"/>
                <xs:element ref="statistics"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="statistics">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="price" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:decimal">
                                <xs:attribute name="date" type="xs:date" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-statistics-per-day">
            <xs:selector xpath="price"/>
            <xs:field xpath="@date"/>
        </xs:unique>
    </xs:element>

    <xs:element name="price">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="pricePerKWh">
                    <xs:attribute name="date" type="xs:date"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="pricePerKWh">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="2"/>
            <xs:maxInclusive value="20"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Shraggen/XML/xml-content/database/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<energie-data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database.xsd">
    <energie-plant>
        <plant>
            <id>1</id>
            <name>Aarau</name>
            <status>true</status>
            <statistics>
                <price date="2021-01-15">10.25</price>
                <price date="2022-01-17">9.75</price>
                <price date="2022-03-20">11.50</price>
                <price date="2022-11-09">13.00</price>
                <price date="2023-01-02">14.00</price>
                <price date="2023-01-03">16.00</price>
                <price date="2023-01-04">9.00</price>
                <price date="2023-01-05">18.50</price>
                <price date="2023-01-06">4.00</price>
            </statistics>
        </plant>
        <plant>
            <id>2</id>
            <name>Luzern</name>
            <status>true</status>
            <statistics>
                <price date="2021-01-15">10.00</price>
                <price date="2022-01-17">8.75</price>
                <price date="2022-03-20">15.50</price>
                <price date="2022-11-09">12.00</price>
                <price date="2023-01-01">5.20</price>
            </statistics>
        </plant>
        <plant>
            <id>3</id>
            <name>Bern</name>
            <status>true</status>
            <statistics>
                <price date="2021-01-15">11.25</price>
                <price date="2022-01-17">8.75</price>
                <price date="2022-03-20">12.50</price>
                <price date="2022-11-09">12.00</price>
                <price date="2023-01-01">9.20</price>
            </statistics>
        </plant>
        <plant>
            <id>4</id>
            <name>ZÃ¼rich</name>
            <status>true</status>
            <statistics>
                <price date="2021-01-15">10.25</price>
                <price date="2022-01-17">9.75</price>
                <price date="2022-03-20">11.50</price>
                <price date="2022-11-09">13.00</price>
            </statistics>
        </plant>
        <plant>
            <id>5</id>
            <name>Genf</name>
            <status>false</status>
            <statistics>
                <price date="2021-01-15">10.25</price>
                <price date="2022-01-17">9.75</price>
                <price date="2022-03-20">11.50</price>
                <price date="2022-11-09">13.00</price>
           </statistics>
        </plant>
    </energie-plant>
</energie-data>
